#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# Предпочтительные порты (можешь расширять список)
API_PREF=(8000 18000 28000 38000 48000)
REDIS_PREF=(6379 6380 16379 26379 36379)

is_free_port() {
  local port="$1"
  python3 - <<PY "$port"
import socket, sys
p=int(sys.argv[1])
s=socket.socket()
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
try:
    s.bind(("127.0.0.1", p))
    print("free")
except OSError:
    print("busy")
finally:
    s.close()
PY
}

pick_port_from_list() {
  local -n arr=$1
  for p in "${arr[@]}"; do
    if [[ "$(is_free_port "$p")" == "free" ]]; then
      echo "$p"
      return 0
    fi
  done
  return 1
}

pick_random_free_port() {
  python3 - <<'PY'
import socket
s=socket.socket()
s.bind(("127.0.0.1", 0))
print(s.getsockname()[1])
s.close()
PY
}

# 1) Выбираем свободные порты
API_BIND_PORT="$(pick_port_from_list API_PREF || pick_random_free_port)"
REDIS_PORT="$(pick_port_from_list REDIS_PREF || pick_random_free_port)"

# 2) Токен: если уже есть .env и там есть API_TOKEN — сохраняем
API_TOKEN=""
if [[ -f .env ]]; then
  API_TOKEN="$(grep -E '^API_TOKEN=' .env | head -n1 | cut -d= -f2- || true)"
fi
if [[ -z "${API_TOKEN}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    API_TOKEN="$(openssl rand -hex 32)"
  else
    API_TOKEN="CHANGE_ME_$(date +%s)"
  fi
fi

# 3) Пишем .env (обновляем целиком — это нормально для теста)
cat > .env <<EOF
# autogenerated by bootstrap.sh

#API_TOKEN=${API_TOKEN}

#API_BIND_HOST=127.0.0.1
API_BIND_PORT=${API_BIND_PORT}

REDIS_PORT=${REDIS_PORT}
REDIS_URL=redis://127.0.0.1:${REDIS_PORT}/0

XRAY_API_ADDR=127.0.0.1:10085
XRAY_SERVICE=xray
XRAY_INBOUND_TAG=vless-in
EOF

echo "[OK] Selected ports: API=${API_BIND_PORT}, REDIS=${REDIS_PORT}"
echo "[OK] .env written"
