# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/hysteria/config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transport/internet/hysteria/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(transport/internet/hysteria/config.proto\x12 xray.transport.internet.hysteria\"\xf3\x02\n\x06\x43onfig\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04\x61uth\x18\x02 \x01(\t\x12\x12\n\ncongestion\x18\x03 \x01(\t\x12\n\n\x02up\x18\x04 \x01(\x04\x12\x0c\n\x04\x64own\x18\x05 \x01(\x04\x12\r\n\x05ports\x18\x06 \x03(\r\x12\x14\n\x0cinterval_min\x18\x07 \x01(\x03\x12\x14\n\x0cinterval_max\x18\x08 \x01(\x03\x12\"\n\x1ainit_stream_receive_window\x18\t \x01(\x04\x12!\n\x19max_stream_receive_window\x18\n \x01(\x04\x12 \n\x18init_conn_receive_window\x18\x0b \x01(\x04\x12\x1f\n\x17max_conn_receive_window\x18\x0c \x01(\x04\x12\x18\n\x10max_idle_timeout\x18\r \x01(\x03\x12\x19\n\x11keep_alive_period\x18\x0e \x01(\x03\x12\"\n\x1a\x64isable_path_mtu_discovery\x18\x0f \x01(\x08\x42\x82\x01\n$com.xray.transport.internet.hysteriaP\x01Z5github.com/xtls/xray-core/transport/internet/hysteria\xaa\x02 Xray.Transport.Internet.Hysteriab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.hysteria.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.xray.transport.internet.hysteriaP\001Z5github.com/xtls/xray-core/transport/internet/hysteria\252\002 Xray.Transport.Internet.Hysteria'
  _globals['_CONFIG']._serialized_start=79
  _globals['_CONFIG']._serialized_end=450
# @@protoc_insertion_point(module_scope)
